### ISSUE TITLE
BUG: "self is not defined" error when using npm package, but not with global UMD one (<script>)

### ISSUE THREAD

**Issue by PhilipAngelinNE** [microsoft/immersive-reader-sdk#398]
As soon as an element with the `launchAsync` function on it renders, I see this error message. Doesn't matter if I don't click, it happens immediately on render.

Using the script tag version works fine.

**Comment by cristobal-buenrostro** [comment]
Hi @PhilipAngelinNE can you let me know if is that happening for any of our [samples](https://github.com/microsoft/immersive-reader-sdk/tree/dev/js/samples)? Or please let me know what framework/language you are using to try to reproduce the issue.

**Comment by cristobal-buenrostro** [comment]
Is there any possibility you can share a small project that reproduces the issue? We don't have a NextJs sample for now. I also verified our two react samples and are working fine.

**Comment by cristobal-buenrostro** [comment]
please check my fork https://github.com/cristobal-buenrostro/immersive-reader-bug

It is working now using dynamic loading.
The reason is because [next prerenders](https://nextjs.org/docs/basic-features/pages#pre-rendering) the page in server side but IR must be loaded on client side only.

using dynamic loading IR is only loaded in client side, but IR logic must be located in a separate component.
