### ISSUE TITLE
Line Reader options appear disabled when they previously did not

### ISSUE THREAD

**Issue by benvillalobos** [microsoft/immersive-reader-sdk#518]
Relevant issue: https://github.com/microsoft/vscode-edu-extension/issues/1913 let me know if you need access to the repo.

![LineFocus](https://private-user-images.githubusercontent.com/148834117/321914849-f5748d28-b997-4953-9929-73ad77436129.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzUxMjgsIm5iZiI6MTcxOTMzNDgyOCwicGF0aCI6Ii8xNDg4MzQxMTcvMzIxOTE0ODQ5LWY1NzQ4ZDI4LWI5OTctNDk1My05OTI5LTczYWQ3NzQzNjEyOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNzAwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWYyMmNhNGQwMjFiMTJjZjA0NDYwN2Y4ZTE2NjNkMjJiOWExOGFlMmIyZTM2OGExYTQ4NWVhYjFiYWU3MWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HPgkrdPVA1BcIJoOTQGPYoJSA2eSq-9xETI1kOjH_KI)

The `3 line` and `5 line` options in Line Focus show as grey and unclickable in browser-sizes where they previously showed as enabled. See more detailed information in the link above.

Has the behavior here changed intentionally?

**Comment by cristobal-buenrostro** [comment]
@benvillalobos I already verified with the team, this is an expected behavior. The line focus available depends on the **text size** and the **content** (total number of lines visible in the screen). All the cases mentioned in the linked issue above are making sense; the content in those samples is pretty short; for instance, in a content with 6 lines of text is expected to have the 5 lines button disabled.
If you change the text size in IR itself, you will also notice how the buttons are enable/disable accordingly.

We don't see any issue here.

**Comment by cristobal-buenrostro** [comment]
closing this issue
