### ISSUE TITLE
Safari webview on iOS is not populated correctly

### ISSUE THREAD

**Issue by FilipWennerdahl** [microsoft/immersive-reader-sdk#86]
When starting Immersive Reader through the javascript sdk on a iOS Safari webview it displays a blank page.
Looking inside the iframe added to the body, the div containing the react app is not populated:

![Screenshot 2019-09-06 at 12 14 16](https://user-images.githubusercontent.com/23334491/64420860-84a10280-d0a0-11e9-9469-65c6082a2b53.png)

When testing on the electron version of our app using the same code, the div is correctly populated:
![Screenshot 2019-09-06 at 12 23 39](https://user-images.githubusercontent.com/23334491/64421152-30e2e900-d0a1-11e9-93dc-2059f73aa50e.png)

**Comment by YanirShahak** [comment]
@FilipWennerdahl , is there a way for you to get console logs from the Safari WebView?

**Comment by robinwassen** [comment]
<img width="984" alt="Screenshot 2019-09-09 at 16 31 32" src="https://user-images.githubusercontent.com/302151/64539989-c095cb00-d31f-11e9-8dee-d70955bdcff8.png">

I am fairly sure that the `getOS()` function returns undefined when it tries to determine the fullscreen capability - so a default case to disallow fullscreen when the OS could not be determined would solve it.

Would guess the reason why we encounter this issue is that we override the user-agent string in the app.

**Comment by robinwassen** [comment]
Worth mentioning is that since this is in the iFrame side of the code we will not be able to make a PR to fix this - so it has to be done by MS.

**Comment by kenatulic** [comment]
Any updates on this @metanMSFT ?

**Comment by dylankil** [comment]
@kenatulic PR of fix to the web app is in review and should be available to test after next deployment. I'll give a shout next time we deploy the app.

**Comment by kenatulic** [comment]
Thanks @dylankil, looking forward to it.

**Comment by dylankil** [comment]
@kenatulic Fix has been deployed. Please test at your earliest convenience and let us know if this issue has been resolved.

**Comment by FilipWennerdahl** [comment]
@dylankil Hey, the issue is now fixed on iOS 13 but unfortunately we are still having the same problem as @robinwassen mentioned above on iOS 12, 11 and 10.
I suspected the implemented fix for getting the OS when using an overridden user-agent was iOS 13 specific.
