### ISSUE TITLE
Line breaks is stripped from the content for chrome webview

### ISSUE THREAD

**Issue by FilipWennerdahl** [microsoft/immersive-reader-sdk#87]
Line breaks from example "p" and "br" tags is stripped when using a webview on chrome apps.
Using the same code for both our chrome and electron app (except for using webview on chrome) results in different results.

Correct format using an iframe:
![Screenshot 2019-09-06 at 15 04 57](https://user-images.githubusercontent.com/23334491/64430197-06505a80-d0b8-11e9-8650-dae1974b0977.png)

Incorrect format using a chrome webview:
![Screenshot 2019-09-06 at 15 07 07](https://user-images.githubusercontent.com/23334491/64430200-081a1e00-d0b8-11e9-8ae6-0200cc3acca3.png)

**Comment by YanirShahak** [comment]
@FilipWennerdahl , will it be possible for you to share the requests & responses to our API?
I would like to see if the issue is on the way up or down.

**Comment by robinwassen** [comment]
I have done some investigation of this by checking what we actually send to launchAsync.

### iFrame method (Electron app)

**Content passed in to the SDK:**

```
content.chunks[0]
{content: "First line of text.↵Second line of text.↵Third line of text.↵"}
content.chunks[0].content.charAt(19) == '\n'
true
```

### WebView method (Chrome app)

```
content.chunks[0]
{content: "First line of text.Second line of text.Third line of text."}
content.chunks[0].content.charAt(19) == '\n'
false
```

The problem is on our side - since both Electron and Chrome app the same code it must be some diff between the Chrome versions that causes our line breaks to disappear.

This ticket can be closed.

**Comment by robinwassen** [comment]
Some further investigation into why we had this issue - the problem was that we took the HTML-content, added it to a HTML-element in JS for pre-processing which was never rendered. 

Newer versions of Chrome does not return the \n character when innerText encounters a br-element if the element is not rendered.

**Solutions:**
- Manually add \n characters during the pre-processing of the content
- Add the content to the DOM so it is rendered and br-elements return a newline

Reported this as a bug to the Chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=1003726
